import yaml
import os

TARGET_DIRECTORY = 'data_test'

story_names = dict(
    HumanMusic = "We Play Human Music",
    CatGone = "A Cat That Really Was Gone",
    Duelist = "The Duelist in Purple Armor",
    Horok = "The Adventures of Horok Ra",
    CitySlickers = "City Slickers and Hayseeds",
    DeniedOps = "Denied Operations",
    SemperShil = "Semper Shil'vati",
    ChaosAndMayhem = "Chaos and Mayhem",
    DependentSpouse = "Dependent Spouse",
    JustOneDrop = "Just One Drop",
    FireWithin = "Fire Within",
    TopLasgun = "Top Lasgun",
    AlienNation = "Alien Nation",
    BlueBlood = "The Blue Blood",
    GoingNative = "Going Native",
    StreetFighter = "Streetfighter",
    FarAway = "Far Away",
    Loyalist = "Loyalist/Growing Up Alien",
    PianoMan = "The Piano Man",
    Lifeguards = "Lifeguards and Amazons",
    CulturalExchange = "Cultural Exchange",
    ClawsOfFate = "Claws of Fate",
    InForPenny = "In for a Penny",
    NoSeparatePeace = "No Separate Peace",
    Insurgent = "Insurgent",
    Untitled = "Untitled",
    Marauder = "The Marauder",
    HumanStudies = "Human Studies",
    TourDownUnder = "A Tour Down Under",
    WesternInsurgency = "The Western Insurgency",
    SocialEngineering = "Social Engineering",
    TheCook = "The Cook",
    Shadows = "Shadows in the Berkshires",
    DearJournal = "Dear Journal",
    OfferYouCantRefuse = "An offer they can't refuse",
    OnceRebel = "Once a Rebel",
    RunningWithThePack = "Running with the Pack",
    Astray = "Astray",
    Pizzaman = "Tales of a Post Invasion Pizzaman",
    UnwelcomeGuests = "The Unwelcome Guests",
    IndependenciaFilipina = "La Independencia Filipina",
    NoGoodDeed = "No Good Deed",
    FireTeamFloofy = "Fire Team Floofy",
    HuntingMaus = "Hunting a Maus",
    DivedeAndConquer = "Divede and Conquer",
    HellFury = "Hell Hath No Fury",
    Refractor = "Refractor",
    Stray = "Stray",
    PaxImperia = "Pax Imperia",
    AppalachiaCalling = "Appalachia Calling",
    ImperiumsHeart = "The way to an imperium's heart",
    SonsOfThunder = "Sons of Thunder",
    TuroxAndLeopard = "The Turox and the Leopard",
    SalvagedPast = "Salvaged Past",
    BloodForParadise = "Blood for Paradise",
    ToxicSands = "Toxic Sands",
    EagleSprings = "Eagle Springs",
    LlanosMestanas = "Llanos Mestanas",
    LegionOfMonsters = "Legion of Monsters",
    FallingUpward = "Falling Upward",
    GameBoi = "Game Boi",
    CryptidChronicle = "The Cryptid Chronicle",
    ContractedHuman = "Contracted Human",
    Marshal = "Marshal",
    Anonymous = "Anonymous",
    Candyman = "Candyman",
    Outcasts = "The Outcasts",
    StoneMountain = "Stonemountain",
    SuperiorAndSubordinate = "The Subordinate and the Superior",
    BeingAMan = "Being a Man",
    UnfortunateChance = "Unfortunate Chance",
    ConvenientNarrative = "Convenient Narrative",
    ColdFront = "Cold Front",
    JanissaryJoyRide = "Janissary: The Joy Ride",
    SemperImperialis = "Semper Imperialis",
    LockedUpInLowOrbit = "Locked Up In Low Orbit",
)

story_connections = [
    ('SemperShil', 'FarAway'),
    ('SemperShil', 'DependentSpouse'),
    ('SemperShil', 'FireWithin'),
    ('SemperShil', 'TopLasgun'),
    ('SemperShil', 'CatGone'),
    ('FireWithin', 'StreetFighter'),
    ('FireWithin', 'GoingNative'),
    ('GoingNative', 'InForPenny'),
    ('GoingNative', 'TopLasgun'),
    ('InForPenny', 'ClawsOfFate'),
    ('JustOneDrop', 'GoingNative'),
    ('JustOneDrop', 'CitySlickers'),
    ('JustOneDrop', 'PianoMan'),
    ('JustOneDrop', 'CulturalExchange'),
    ('JustOneDrop', 'HumanMusic'),
    ('JustOneDrop', 'DeniedOps'),
    ('DeniedOps', 'Horok'),
    ('DeniedOps', 'ClawsOfFate'),
    ('DeniedOps', 'ChaosAndMayhem'),
    ('DeniedOps', 'HumanMusic'),
    ('DeniedOps', 'CulturalExchange'),
    ('Horok', 'Duelist'),
    ('Horok', 'ClawsOfFate'),
    ('Horok', 'BloodForParadise'),
    ('Horok', 'RunningWithThePack'),
    ('Astray', 'RunningWithThePack'),
    ('CitySlickers', 'PianoMan'),
    ('CitySlickers', 'ChaosAndMayhem'),
    ('ChaosAndMayhem', 'Lifeguards'),
    ('ChaosAndMayhem', 'DependentSpouse'),
    ('ChaosAndMayhem', 'InForPenny'),
    ('ChaosAndMayhem', 'PianoMan'),
    ('ChaosAndMayhem', 'BlueBlood'),
    ('ChaosAndMayhem', 'AlienNation'),
    ('FarAway', 'TopLasgun'),
    ('HumanMusic', 'TopLasgun'),
    ('Loyalist', 'DependentSpouse'),
    ('AlienNation', 'CatGone'),
    ('AlienNation', 'SemperShil'),
    ('AlienNation', 'BlueBlood'),
    ('AlienNation', 'Shadows'),
    ('Insurgent', 'BlueBlood'),
    ('NoSeparatePeace', 'TopLasgun'),
    ('NoSeparatePeace', 'HumanMusic'),
    ('JustOneDrop', 'TopLasgun'),
    ('JustOneDrop', 'Loyalist'),
    ('DeniedOps', 'ToxicSands'),
    ('DeniedOps', 'EagleSprings'),
    ('FarAway', 'EagleSprings'),
    ('FarAway', 'DeniedOps'),
    ('FarAway', 'ChaosAndMayhem'),
    ('Untitled', 'AlienNation'),
    ('SemperShil', 'Untitled'),
    ('SemperShil', 'ChaosAndMayhem'),
    ('ClawsOfFate', 'FireWithin'),
    ('LegionOfMonsters', 'ChaosAndMayhem'),
    ('FarAway', 'Marauder'),
    ('FarAway', 'ChaosAndMayhem'),
    ('FarAway', 'TopLasgun'),
    ('EagleSprings', 'GameBoi'),
    ('ChaosAndMayhem', 'JustOneDrop'),
    ('ChaosAndMayhem', 'HumanMusic'),
    ('ChaosAndMayhem', 'DependentSpouse'),
    ('AlienNation', 'Marauder'),
    ('Anonymous', 'ChaosAndMayhem'),
    ('Anonymous', 'AlienNation'),
    ('CryptidChronicle', 'DeniedOps'),
    ('CryptidChronicle', 'ChaosAndMayhem'),
    ('HumanMusic', 'BlueBlood'),
    ('HumanMusic', 'AlienNation'),
    ('Outcasts', 'FarAway'),
    ('Outcasts', 'Candyman'),
    ('EagleSprings', 'HuntingMaus'),
    ('StoneMountain', 'DeniedOps'),
    ('StoneMountain', 'ChaosAndMayhem'),
    ('HuntingMaus', 'BeingAMan'),
    ('HuntingMaus', 'SuperiorAndSubordinate'),
    ('BeingAMan', 'SuperiorAndSubordinate'),
    ('TheCook', 'CitySlickers'),
    ('Candyman', 'InForPenny'),
    ('Candyman', 'Outcasts'),
    ('JanissaryJoyRide', 'ChaosAndMayhem'),
    ('JanissaryJoyRide', 'DeniedOps'),
    ('JanissaryJoyRide', 'GoingNative'),
    ('JanissaryJoyRide', 'JustOneDrop'),
    ('CryptidChronicle', 'ChaosAndMayhem'),
    ('StoneMountain', 'JustOneDrop'),
    ('StoneMountain', 'DeniedOps'),
    ('StoneMountain', 'TopLasgun'),
    ('EagleSprings', 'ChaosAndMayhem'),
]


def rename_id(story_id):
    _id = ''.join(['_' + l.lower() if l.isupper() else l for l in story_id])
    if _id[0] == '_':
        _id = _id[1:]
    return _id

for old_story_id, story_name in story_names.items():
    story_id = rename_id(old_story_id)
    print(f"{story_id}: {story_name}")

    story_id_connections = []

    for (story_a, story_b) in story_connections:
        if story_a == old_story_id:
            story_id_connections.append(rename_id(story_b))

    story_dict = dict(
        id=story_id,
        name=story_name,
        link="",
        author="",
        connections=[c for c in story_id_connections],
    )
    
    target_filename = os.path.join(TARGET_DIRECTORY, f"{story_id}.yaml")
    with open(target_filename, 'w') as yaml_file:
        yaml.dump(story_dict, yaml_file, default_flow_style=False, sort_keys=False)
